services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $bundleConfig: '%huh_versions%'

  HeimrichHannot\VersionsBundle\DataContainer\VersionsContainer:
    public: true

  HeimrichHannot\VersionsBundle\Version\VersionControl:
    public: true