services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\VersionsBundle\DataContainer\VersionsContainer:
    public: true

  HeimrichHannot\VersionsBundle\Version\VersionControl:
    public: true